version: '3.5'

# This is needed for making locomotive instance communicate w/ master odoo instance in dev mode
# If you don't put odoo in the same composition, just add this shared network and an alias to the odoo one.
# IMPORTANT: to make this work w/ `run --rm` you have to pass `--use-aliases`.
networks:
  shopinvader-shared-odoo-net:
    name: shopinvader-shared-odoo-net

services:
  db:
    image: mongo:3
    volumes:
      - .db:/data/db
  locomotive:
    ports:
      - 3000:3000
    # In production never never never use latest !
    # use a specific tag image in order to be sure
    # of what you install
    image: quay.io/akretion/shopinvader:latest
    links:
      - db
    volumes:
      - .loco-data/tmp:/usr/src/app/tmp:rw
      - .loco-data/log:/usr/src/app/log:rw
      - .loco-data/public/sites:/usr/src/app/public/sites:rw
      - .loco-data/public/uploaded_assets:/usr/src/app/public/uploaded_assets:rw
    networks:
      default:
      shopinvader-shared-odoo-net:
        aliases:
          # reach locomotive w/ this alias (eg: from odoo or any other service)
          - locomotive.local
  wagon:
    image: quay.io/akretion/shopinvader-wagon:latest
    ports:
      - 3333:3333
    volumes:
      # NOTE: to make this work the do-co file should stay in the root of your shopinvader theme
      - .:/workspace
    networks:
      default:
      shopinvader-shared-odoo-net:
        aliases:
          - locomotive.wagon
